### ISSUE TITLE
Stat polkit agent when using startx?

### ISSUE THREAD

**Issue by IPlayZed** [sandsmark/polkit-dumb-agent#3]
Hi, I am using dwm and start it with startx. I was wondering how can I start this so when I need it it can authenticate? If I start it .xinitrc by `polkit-dumb-agent &` it only shows an auth dialog, but it is stuck in a loop if I try to authenticate until I cancel it. Thanks a lot!

**Comment by alpabrz** [comment]
Don't know whether that helps, but you may use e.g. `dex` and comparable utilities to start desktop files (this project provides one). Just move the `.desktop` file into one of the autostart directories (if your distro doesn't do it already) and you should be able to start it using `dex -a` (put it in your .xinitrc). But be watchful, that also starts other applications that are provided in one of the autostart-directories. [Further information from the ArchWiki about autostarting applications.](https://wiki.archlinux.org/title/XDG_Autostart)
[Optionally, just use `dex /path/to/desktop/file` to only start `polkit-dumb-agent`].


I used that in combination with `polkit-dumb-agent`, and it seemed to work fine. But because of other issues and not fully understanding polkit I switched to `lxqt-policykit`, which seems to be a more complete polkit-agent implementation. So can't speak for it now.

Kind regards!

**Comment by IPlayZed** [comment]
> Don't know whether that helps, but you may use e.g. `dex` and comparable utilities to start desktop files (this project provides one). Just move the `.desktop` file into one of the autostart directories (if your distro doesn't do it already) and you should be able to start it using `dex -a` (put it in your .xinitrc). But be watchful, that also starts other applications that are provided in one of the autostart-directories. [Further information from the ArchWiki about autostarting applications.](https://wiki.archlinux.org/title/XDG_Autostart)
> [Optionally, just use `dex /path/to/desktop/file` to only start `polkit-dumb-agent`].
> 
> I used that in combination with `polkit-dumb-agent`, and it seemed to work fine. But because of other issues and not fully understanding polkit I switched to `lxqt-policykit`, which seems to be a more complete polkit-agent implementation. So can't speak for it now.
> 
> Kind regards!

I have tested this but this does not seem to work. The program is started, but the looping issue is the same. I guess I will check out the lxqt one then :(

**Comment by alpabrz** [comment]
Ouh sorry, it seems like I didn't read the issue description fully :/ Yes, that looping issue was exactly why I switched to the lxqt stuff :( Don't quote me on that, but for me IIRC it worked when entering the root password, so probably has something to do with polkit rules.

**Comment by IPlayZed** [comment]
I installed polkit from the repos and did not config it whatsoever. The AUR package had the same problem. Maybe I will post about this there as well, bc this repo is not active so much.

**Comment by IPlayZed** [comment]
It looks like this repo is dead and the problem was not resolved based on activity. I will modify the Arch wiki to not that this program has this bug.

**Comment by IPlayZed** [comment]
I closed as this repository is dead seems like.
